export const SITE_URL = 'https://hkweb.nl';
export const SITE_NAME = 'HKweb';
export const SITE_DESCRIPTION =
    'Hans Kuijpers is frontend developer bij HKweb. Hij bouwt snelle, toegankelijke websites en webshops met Joomla, Magento, Craft CMS en Next.js.';
export const SITE_TITLE = 'Hans Kuijpers';
export const SITE_SUBTITLE = 'Happy Frontend Developer';
export const SITE_SKILLS = 'Joomla | Magento | Craft CMS | NextJS';
export const SITE_EMAIL = 'info@hkweb.nl';
export const SITE_PHONE = '+31654224518';

// 1200×630 share image, generated by scripts/generate-hero-images.mjs.
export const OG_IMAGE = {
    url: `${SITE_URL}/images/og/hans-2020-1200x630.jpg`,
    width: 1200,
    height: 630,
    alt: 'Hans Kuijpers lacht naar de camera'
};

export const SOCIAL_PROFILES = [
    { icon: 'github', label: 'GitHub', url: 'https://github.com/hans2103' },
    { icon: 'codepen', label: 'CodePen', url: 'https://codepen.io/hans2103' },
    { icon: 'linkedin', label: 'LinkedIn', url: 'https://linkedin.com/in/hans2103' },
    { icon: 'instagram', label: 'Instagram', url: 'https://instagram.com/hans2103' },
    { icon: 'behance', label: 'Behance', url: 'https://behance.net/hans2103' }
];
