// src/layout/hero.tsx

import Head from 'next/head';
import type { ComponentProps } from 'react';

import { SITE_SUBTITLE, SITE_TITLE } from '../../lib/constants';
import { css } from '../../panda/css';
import { Box, Flex, styled } from '../../panda/jsx';
import Heading from '../components/heading';

// Static variants generated by scripts/generate-hero-images.mjs — keep the
// widths in sync with that script.
const HERO_WIDTHS = [640, 750, 828, 1080, 1200, 1920, 2048];
const srcSet = (ext: string) =>
    HERO_WIDTHS.map((w) => `/images/hero/hans-2020-${w}.${ext} ${w}w`).join(', ');

// Covers the hero like next/image `fill` + objectFit did, but via a class so
// no inline style attribute is needed (keeps CSP style-src free of 'unsafe-inline').
const heroImageClass = css({
    position: 'absolute',
    inset: '0',
    width: 'full',
    height: 'full',
    objectFit: 'cover',
    color: 'transparent'
});

// styled(Heading, ...) is fine — Heading is a regular React component, not a
// Panda pattern, so the recipe's base classes propagate. Don't wrap Panda's
// Flex/Box this way: it drops the pattern's `display: flex` / `box-sizing`.
const HeroHeading = styled(Heading, {
    base: { color: 'currentColor', fontSize: 'xxl' }
});

// The subtitle looks like an h2 but is not a section heading, so render it as
// <p>. Panda's styled() swallows an `as` prop, so pass it to Heading here.
const Subtitle = (props: Omit<ComponentProps<typeof Heading>, 'level' | 'as'>) => (
    <Heading level={2} as="p" {...props} />
);

const HeroSubheading = styled(Subtitle, {
    base: { color: 'currentColor', fontSize: 'xl' }
});

const Hero = () => (
    <Flex
        position="relative"
        direction="column"
        width="full"
        height="heroHeight"
        minHeight="heroMin"
        backgroundColor="base">
        <Head>
            <link
                rel="preload"
                as="image"
                type="image/avif"
                imageSrcSet={srcSet('avif')}
                imageSizes="100vw"
                fetchPriority="high"
            />
        </Head>
        <Box as="figure" m="0" height="full" overflow="hidden">
            <picture>
                <source type="image/avif" srcSet={srcSet('avif')} sizes="100vw" />
                <source type="image/webp" srcSet={srcSet('webp')} sizes="100vw" />
                <img
                    src="/images/hero/hans-2020-1920.jpg"
                    srcSet={srcSet('jpg')}
                    sizes="100vw"
                    width={3360}
                    height={2240}
                    alt="Hans Kuijpers lacht naar de camera"
                    fetchPriority="high"
                    decoding="async"
                    className={heroImageClass}
                />
            </picture>
        </Box>
        <Box zIndex={1} color="hero" textShadow="headline" pb="pageBottom" pl="pageInline">
            <HeroHeading level={1}>{SITE_TITLE}</HeroHeading>
            <HeroSubheading>{SITE_SUBTITLE}</HeroSubheading>
        </Box>
    </Flex>
);

export default Hero;
